version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./run docker build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: ./run docker test
  integration-test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ./run docker test-integration
  release:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: echo "Releaseing..."

workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - test:
          requires:
            - build
      - integration-test:
          requires:
            - build
      - approve-release:
          type: approval
          requires:
            - test
            - integration-test
      - release:
          requires:
            - approve-release
